# File: .github/workflows/workflow.yml
name: GitHub Actions Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v2
     - uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
     - run: |
         az account management-group create --name ghActionsTestMgCli
         az account management-group list
         az account management-group show --name environmentMG
         az account management-group show --name ghActionsTestMgCli
