name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Install Az PowerShell Module
        uses: azure/powershell@v1
        with:
          inlineScript: |
            if (Get-Module -ListAvailable -Name Az.Resources) {
              Write-Host "Module exists"
            }
            else {
              Write-Host "Module does not exist"
            }
          azPSVersion: '4.3.0'
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run Azure PowerShell login script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $azureAplicationId = "e41b601f-22b1-45f9-a9b6-26cdc7d35b48"
            $azureTenantId= "8de3d3fb-4ae1-4c39-99e0-bede3ca0a96c"
            $azurePassword = ConvertTo-SecureString "yxXt.eNGyzXE6cu29NvGQ~3e2E8.P69stJ" -AsPlainText -Force
            $psCred = New-Object System.Management.Automation.PSCredential($azureAplicationId , $azurePassword)
            Connect-AzAccount -Credential $psCred -TenantId $azureTenantId  -ServicePrincipal
          azPSVersion: '4.3.0'
      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup -Name "rg-kv-useast-01"
          azPSVersion: '4.3.0'
      - name: Run Management Group Deployment PS script
        run: .\deployManagementGroups.ps1
        shell: powershell
      - run: echo "🍏 This job's status is ${{ job.status }}."

#Install-Module -Name AzureRM.ManagementGroups -AllowPrerelease 

      # - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      # - name: Log in with Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: '${{ secrets.AZURE_CREDENTIALS }}'
